### PR TITLE
Set RollForward=LatestMajor so the tool will run with newer runtimes.

### PR DESCRIPTION
**Pull request by alexrp**
This is to fix issues like this on .NET 5.0:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.0-preview.8.20407.11 at [C:\hostedtoolcache\windows\dncs\5.0.100-preview.8.20417.9\x64\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=win10-x64
```

### CODE REVIEW

**Comment by alexrp** [comment]
Ping?

**Comment by jcansdale** [comment]
@alexrp sorry I dropped the ball on this! I have too many GitHub notifications and missed this. 😊 

This looks like a neat solution that I didn't know about. I'll see about getting it merged. Thanks for the suggestion!

**Comment by alexrp** [comment]
No worries. Thanks for taking a look. 🙂

**Review by jcansdale — COMMENTED** [review]
LGTM!

**Comment by jcansdale** [comment]
@alexrp This has been merged/published. If you could confirm it's working as expected, that would be great! 🙏🏻

**Comment by alexrp** [comment]
@jcansdale Sorry for the delay. I can confirm that `gpr` now works w/o the `DOTNET_ROLL_FORWARD` environment variable set.

**Pull request merged**
