### PR TITLE
Support using private instance repo URL in upload

### PR DESCRIPTION
**Pull request by ritchxu**
This PR makes it possible to use a private instance's repo URL when pushing packages.

### CODE REVIEW

**Review by jcansdale — CHANGES_REQUESTED** [review]
This is looking good. 😄 

Could we add a test for the `NugetPackageEndpoint` returned by `BuildOwnerAndRepositoryFromUrl`?
   
Something along the lines of this:
https://github.com/jcansdale/gpr/blob/master/test/GprTool.Tests/NuGetUtilitiesTests.cs#L193

Note, `BuildOwnerAndRepositoryFromUrlFromNupkg` uses the repository URL from inside the .nupkg file. This would be a simpler test for `BuildOwnerAndRepositoryFromUrl`.

**Comment by ritchxu** [comment]
Test added 👌🏼

**Comment by ritchxu** [comment]
@jcansdale circling back on this, any further comments before merging?

**Review by jcansdale — APPROVED** [review]
This looks good! I'm happy with it if you are. 😄

**Pull request merged**
