### PR TITLE
Strip any NuGet version metadata

### LINKED ISSUE #92: Specifying the version when pushing doesn't work for stripping build metadata
As per our discussion here: https://github.community/t/bug-nuget-support-build-metadata-properly/117606/15

It seems `gpr push "*.nupkg" --version 1.0.0` doesn't work if the package's version is `1.0.0+BuildMetadata` because the two versions are considered to be equivalent.

### PR DESCRIPTION
**Pull request by jcansdale**
GitHub Packages isn't currently compatible with version metadata. Packages with metadata will upload successfully, but won't be accessible. This PR strips any metadata before uploading the package.

When a package version includes metadata, the output should look like:

```
Found 1 package.
[PackageWithMetadata.1.0.0.nupkg]: Stripping Metadata: metadata, from Version: 1.0.0+metadata
[PackageWithMetadata.1.0.0.nupkg]: Repository url: https://github.com/jcansdale-test/foo. Version: 1.0.0. Size: 5314 bytes.
[PackageWithMetadata.1.0.0.nupkg]: Uploading package.
```

### How to test

1. Copy this [nuget.config](https://github.com/jcansdale/gpr/blob/master/nuget.config) into a new directory
2. From the same directory do `dotnet tool update gpr --version 0.1.237-gadc903af74 -g`
3. Try pushing a package with a version that includes metadata (e.g. `gpr push your.pkg -k <PAT>`)

Fixes #92

### CODE REVIEW

**Comment by jcansdale** [comment]
Hey @peters, if you have a moment could you review this PR? 🙏

**Comment by PathogenDavid** [comment]
Can confirm this fixes #92 https://github.com/PathogenPlayground/GitHubPackagesBuildMetadataTest/actions/runs/216709279

For the sake of completeness, I tested with an explicit `--version` and can confirm it also works as expected: https://github.com/PathogenPlayground/GitHubPackagesBuildMetadataTest/actions/runs/216713992

Thanks for getting that fixed!

**Comment by jcansdale** [comment]
@PathogenDavid excellent, thanks for testing this!

**Comment by jcansdale** [comment]
This has since been fixed in GitHub Packages.

- NuGet normalizes versions on publish
https://github.com/github/releases/issues/1067

No need to merge this.

**Pull request closed without merging**
